# Jekyll Configuration
theme: jekyll-theme-minimal

# Basic Information
title: Yung-Ching Sun
description: Robotics Ph.D. Student at Georgia Tech
logo: assets/img/ycs_photo_12.jpg

# Contact & Social Links
url_github: https://github.com/ycsun2113
url_email: ysun767@gatech.edu
# url_email: ycs@umich.edu
url_linkedin: https://www.linkedin.com/in/yung-ching-sun
url_cv: docs/CV_0421.pdf
# url_steam: https://steamcommunity.com/id/silvery107
url_scholar: https://scholar.google.com/citations?user=boW1AIoAAAAJ&hl=en

# Optional Settings
# chinese_name: assets/img/name_kaiti.svg
# google_analytics: G-H2H5LCSDZ9
google_analytics: G-16P0NYG4D8
